### ISSUE TITLE
Remove lombok to support IDE's without lombok plugin

### ISSUE THREAD

**Issue by joakime** [ati90ati/bugreport-wiremock-webflux-hanging#1]
The current codebase is incompatible with Eclipse IDE and IntelliJ (CE and Pro).
The codebase cannot be compiled by either environment (`log` and `getNumber` report as build failures).

**Comment by ati90ati** [comment]
It is vert interesting, because for me it works just fine.
I'll update the documentation on what I am using to run the project. 

Actually I am using IntelliJ Ultimate with bundled JDK and OpenJDK 11.0.2 and my OS is Ubuntu 18.04.

**Comment by joakime** [comment]
I'm using on OpenJDK 11.0.2+9 as well.

Tried on both OSX 10.12.6
and Fedora Core 28

Command line is fine, but there's something about loading the project into an IDE that it just does not like.

```
/Users/joakim/Code/Jetty/stackoverflow/bugreport-wiremock-webflux-hanging/src/main/java/org/anagy/bugreport/client/client1/Service1Client.java
Error:(29, 32) java: cannot find symbol
  symbol:   variable log
  location: class org.anagy.bugreport.client.client1.Service1Client
Error:(30, 33) java: cannot find symbol
  symbol:   variable log
  location: class org.anagy.bugreport.client.client1.Service1Client
/Users/joakim/Code/Jetty/stackoverflow/bugreport-wiremock-webflux-hanging/src/main/java/org/anagy/bugreport/client/client2/Service2Client.java
Error:(29, 32) java: cannot find symbol
  symbol:   variable log
  location: class org.anagy.bugreport.client.client2.Service2Client
Error:(30, 33) java: cannot find symbol
  symbol:   variable log
  location: class org.anagy.bugreport.client.client2.Service2Client
/Users/joakim/Code/Jetty/stackoverflow/bugreport-wiremock-webflux-hanging/src/main/java/org/anagy/bugreport/controller/NumberController.java
Error:(38, 32) java: cannot find symbol
  symbol:   method getNumber()
  location: class org.anagy.bugreport.client.client1.Client1Dto
Error:(39, 32) java: cannot find symbol
  symbol:   method getNumber()
  location: class org.anagy.bugreport.client.client2.Client2Dto
```

**Comment by joakime** [comment]
It seems the lombok layer is the cause.
I cannot install the lombok plugin for the IDEs due to corporate security configuration (lombok is rejected as vulnerable).
Can you make this project/replication not use lombok?

It will also reduce the complexity of the issue even further, focusing the effort, and helping narrow down the problem space.

**Comment by ati90ati** [comment]
Sorry, I forgot the fact that the lombok plugin should be installed. 

Sure, I'll remove the lombok plugin in a new commit.

**Comment by ati90ati** [comment]
I've removed the lombok plugin on a new commit.

**Comment by joakime** [comment]
Cool, this version is much more IDE friendly.
Thank you.

Now to see what I discover...
